### DISCUSSION TITLE
Help with Setting Up Maize Glide Docking Scoring in REINVENT

### DISCUSSION THREAD

**Discussion by SAGARSS24** [MolecularAI/maize-contrib#10] [Q&A]
Hi there,
First of all, thank you for developing and maintaining REINVENT and the Maize community, these tools and the surrounding support have been truly transformative in accelerating my drug discovery workflows.

I've been using REINVENT for some time now, mainly leveraging 1D and 2D descriptor-based scoring functions. I am now aiming to incorporate 3D-oriented scoring into my reinforcement learning workflow specifically Glide docking with an MCS constraint.

I understand that Maize workflows can be invoked via REINVENT using the `maize_config` YAML file referenced in the global REINVENT configuration. However, I'm currently unclear about a few aspects and would greatly appreciate guidance on:

---

### **My Questions:**

1. How to set up the **Maize workflow YAML file** correctly for Glide docking with MCS constraints?
2. How to properly configure the `param.toml` file for use with this workflow?
3. How to ensure the workflow is **seamlessly integrated into the REINVENT scoring function configuration**?

---

#### 1. REINVENT Global Configuration (`.toml`):

```toml
[[stage.scoring.component]]
[stage.scoring.component.Maize]
[[stage.scoring.component.Maize.endpoint]]
name = "glide"
weight = 1
transform.type = "reverse_sigmoid"
transform.high = -3
transform.low = -11.5
transform.k = 0.5

params.executable = "/path/to/conda/envs/maize-dev/bin/maize"
params.workflow = "/path/to/work_dir/dock/glide.yml"
params.config = "/path/to/work_dir/dock/test-config.toml"

params.parameters.receptor = "/path/to/glide-grid/grid.maegz"
params.parameters.reference_lig = "/path/to/reference/ligand.maegz"
params.parameters.inp_grid = "/path/to/glide-grid/grid.zip"
params.parameters.constraints = "/path/to/constraints/file.in"
params.parameters.docked_poses_loc = "/path/to/output/poses"

params.debug = true
params.keep = true
params.log = "maize.log"
```

---

#### 2. Maize Glide Docking Workflow (`glide.yml`):

```yaml
# GLIDE
# =====
# Runs docking with Glide (with a REINVENT interface)

name: glide

nodes:
- name: smiles
  type: ReinventEntry
- name: dock
  type: GlideDocking
- name: rnv
  type: ReinventExit
- name: void
  type: Void
- name: isocopy
  type: Copy
- name: bestisomerfilter
  type: BestIsomerFilter
- name: tagfilter
  type: TagFilter
  parameters:
    must_have_tags: ["r_i_docking_score"]
- name: conffilter
  type: BestConformerFilter
- name: saveligs
  type: SaveSingleLibrary

channels:
- sending:
    smiles: out
  receiving:
    dock: inp
- sending:
    dock: out
  receiving:
    isocopy: inp
- sending:
    isocopy: out
  receiving:
    rnv: inp
- sending:
    isocopy: out
  receiving:
    bestisomerfilter: inp
- sending:
    bestisomerfilter: out
  receiving:
    tagfilter: inp
- sending:
    tagfilter: out
  receiving:
    conffilter: inp
- sending:
    conffilter: out
  receiving:
    saveligs: inp
- sending:
    smiles: out_metadata
  receiving:
    void: inp

parameters:

# DO NOT TOUCH: This is the required input parameter
- name: inp
  map:
  - smiles: data

# DO NOT TOUCH: JSON output for REINVENT
- name: out
  map:
  - rnv: data

# MANDATORY: Receptor to use for docking
- name: inp_grid
  map:
  - dock: inp_grid

# OPTIONAL: Reference ligand
- name: reference_lig
  optional: true
  map:
  - dock: reference_lig
```

---

#### 3. Parameter Configuration File (`test-config.toml`):

```toml
scratch = "/tmp"
packages = [
    "maize.steps.mai"
]

[batch]
system = "local"
walltime = "24:00:00"

[glide]
commands.glide = "/path/to/schrodinger/glide"
```

---

### **What I Need Help With:**

1. Whether I’ve correctly set the parameters to enable **MCS-constrained docking** using Glide.
2. If any **additional tags, parameters, or modules** are needed in the YAML or TOML files to make this work.
3. Whether there are any existing **example projects or minimal working examples** available for this specific REINVENT-Maize integration.

Additionally this the error am getting ```KeyError: 'Node of type reinvententry not found in the registry. Have you imported the node class definitions?```

Thank you again.

Warm regards,
**Sagar**
